-- AlterTable
ALTER TABLE "LiquidityAsset" ADD COLUMN "symbol" TEXT NOT NULL DEFAULT '';
ALTER TABLE "LiquidityAsset" ADD COLUMN "quantity" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "LiquidityAsset" ADD COLUMN "goldWeightBaht" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "LiquidityAsset" ADD COLUMN "yieldPercent" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "LiquidityAsset" ADD COLUMN "couponFrequency" TEXT NOT NULL DEFAULT '';
ALTER TABLE "LiquidityAsset" ADD COLUMN "navPerUnit" DOUBLE PRECISION NOT NULL DEFAULT 0;
